# Project information
site_name: ola_taxi_price_prediction_based_on_cluster
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Sandeep Jena
site_description: >-
  DESCRIPTION
# Repository
repo_name: sandeepjena7/ola_taxi_price_prediction_based_on_cluster
repo_url: https://github.com/sandeepjena7/ola_taxi_price_prediction_based_on_cluster

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: green
      accent: lime    
  # logo: scikit-learn-seeklogo.com.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sandeepjena7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sandeepjena777


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/sandeepjena7"  target="_blank" rel="noopener">Sandeep Jena</a>